Module6 task1
htmlacademy-ecmascript/942149-cinemaddict-12 pull request #8
Opened 2020-09-12 18:54 UTC by Kartaviy-arteom

2020-09-17 14:11 UTC, Epsilonnnn requested changes

2020-09-17 14:11 UTC, Epsilonnnn commented on src/presenter/card.js
> +    remove(this._filmComponent);
должно быть так
```
this._filmComponent.remove()
this._popupComponent.remove()
```

ради того, чтобы проверять на null не стоит делать отдельный хелпер, он только вносит беспорядок, так как получается, что есть хелпер `remove` и метод класса `remove`, а само выделение в ф-цию только из-за одной общей проверки в данном случае того не стоит

2020-09-17 14:11 UTC, Epsilonnnn commented on src/presenter/card.js
> +  constructor(filmListElement, changeData, changeMode) {
https://github.com/htmlacademy-ecmascript/942149-taskmanager-12/pull/7#discussion_r488549113

2020-09-19 16:16 UTC, Kartaviy-arteom commented on src/view/popup.js
> +          userComment: null,
у меня это комментарий который может дописать пользователь. Я так понял https://up.htmlacademy.ru/ecmascript/12/project/cinemaddict#resource это данные, которые нужно отдать и если закрываем попап на esc их хранить не нужно

2020-09-22 19:02 UTC, Epsilonnnn commented on src/presenter/card.js
> +      this._changeData(Popup.parseDataToFilm(this._popupComponent._data));
приватные поля лучше не использовать извне

2020-09-29 21:14 UTC, merged